 // This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "ui-kit": {
    "LoadingData": "Loading data...",
    "NoData": "No data",
    "noOptions": "No options",
    "pagination": {
      "currentItems": "Showing from {{start}} to {{end}}",
      "itemsOnPage": "Items on page:",
      "ofPages": "of pages:",
      "totalPagesInfo": "{{current}} of {{total}}"
    },
    "resetAll": "Reset all",
    "search": "Search",
    "selectAll": "Select all"
  }
}

export default Resources;
