 // This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "common": {
    "noOptions": "No options",
    "resetAll": "Reset all",
    "search": "Search",
    "selectAll": "Select all"
  }
}

export default Resources;
